# Generated by Django 5.0.4 on 2024-04-27 18:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellerprofile',
            name='brand_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='sellerprofile',
            name='license_image',
            field=models.ImageField(blank=True, null=True, upload_to='seller_license_images/'),
        ),
        migrations.AddField(
            model_name='sellerprofile',
            name='permit_image',
            field=models.ImageField(blank=True, null=True, upload_to='seller_permit_images/'),
        ),
        migrations.AddField(
            model_name='sellerprofile',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='seller_profile_images/'),
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('house_number_street_area', models.CharField(max_length=100)),
                ('locality_town', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('pincode', models.CharField(max_length=10)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='customerprofile',
            name='address',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='authentication.address'),
        ),
        migrations.AddField(
            model_name='sellerprofile',
            name='address',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='authentication.address'),
        ),
    ]
